server:
  port: 8090

sentry:
  dsn: ${SENTRY_DSN:}
  tracesSampleRate: ${SENTRY_SAMPLE_RATE:1.0}
  enabled: ${SENTRY_ENABLED:false}
  environment: ${SENTRY_ENVIRONMENT:dev}
  use-git-commit-id-as-release: true

spring:
  mvc:
    log-request-details: ${DEBUG_LOG_REQUESTS:false}
  devtools:
    livereload:
      enabled: ${DEVTOOLS_LIVE_RELOAD:false}
    restart:
      enabled: ${DEVTOOLS_RESTART:false}

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:}"
    username: ${DATABASE_USER:}
    password: ${DATABASE_PASSWORD:}

  graphql:
    graphiql:
      enabled: ${GRAPHIQL_ENABLED:true}
    schema:
      printer:
        enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 300s
      key-prefix: "${REDIS_CACHE_PREFIX:graph-cache}:"
      use-key-prefix: true
      enable-statistics: true

    dynamodb:
      table-name: GraphQLCache
      time-to-live: 300s
      endpoint: ${DYNAMO_ENDPOINT:}
      create-table: ${DYNAMO_CREATE_TABLE:true}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI:}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

debug: ${DEBUG:false}

configuration:
  environment: ${ENVIRONMENT:dev}
  database-secret: ${DATABASE_SECRET:}
  scheduler-zone: "${SCHEDULER_ZONE:Europe/London}"
  region: ${AWS_REGION:eu-west-2}
  base-url: "${BASE_URL:http://localhost:8080}"
  mail:
    from-address: ${EMAIL_FROM_ADDRESS:}
    membership-bcc: ${EMAIL_MEMBERSHIP_BCC_ADDRESS:}
    logo: "https://resources.mersthamcc.co.uk/mcc/img/logos/mcc-logo.svg"
    logo-dark: "https://resources.mersthamcc.co.uk/mcc/img/logos/mcc-logo-inverse.svg"
    club-name: ${CLUBNAME:My Cricket Club}
    club-url: "${BASE_URL:http://localhost:8080}"
    footer-text: ${CLUB_ADDRESS:}
  bank-details:
    account-name: ${BANK_ACCOUNT_NAME:Merstham Cricket Club}
    account-number: ${BANK_ACCOUNT_NUMBER:49244507}
    sort-code: ${BANK_ACCOUNT_SORT_CODE:56-00-46}
  cognito:
    user-pool-id: ${COGNITO_USER_POOL_ID:}
  epos-now:
    customer-refresh-cron: "${EPOS_CUSTOMER_REFRESH_CRON:-}"
    create-function-arn: "${EPOS_CREATE_CUSTOMER_FUNCTION_ARN:}"
    dry-run: "${EPOS_DRY_RUN:true}"
  accounting:
    sync-cron: "${ACCOUNTING_SYNC_CRON:-}"
    create-sales-order-arn: "${CREATE_SALES_ORDER_ARN:}"
    create-payment-arn: "${CREATE_PAYMENT_ARN:}"
    get-payments-arn: "${GET_PAYMENTS_ARN:}"
    get-credits-arn: "${GET_CREDITS_ARN:}"
  play-cricket:
    api-token: ${PLAY_CRICKET_API_TOKEN:}
    site-id: ${PLAY_CRICKET_SITE_ID:}
    team-refresh-cron: "${PLAY_CRICKET_TEAM_CRON:-}"
    fixture-refresh-cron: "${PLAY_CRICKET_FIXTURE_CRON:-}"
  webhooks:
    stripe:
      secret: ${STRIPE_WEBHOOK_SECRET:}
      api-key: ${STRIPE_API_KEY:}
      publishable-key: ${STRIPE_PUBLISHABLE_KEY:}
    gocardless:
      secret: ${GOCARDLESS_WEBHOOK_SECRET:}
      access-token: ${GOCARDLESS_ACCESS_TOKEN:}
      sandbox: ${GOCARDLESS_SANDBOX:true}
    paypal:
      client-id: ${PAYPAL_CLIENT_ID:}
      client-secret: ${PAYPAL_CLIENT_SECRET:}
      sandbox: ${PAYPAL_SANDBOX:true}
      webhook-id: ${PAYPAL_WEBHOOK_ID:}
  facebook:
    application-id: ${FACEBOOK_APP_ID}
    application-secret: ${FACEBOOK_APP_SECRET}
    page-id: ${FACEBOOK_PAGE_ID}
    access-token: ${FACEBOOK_PAGE_ACCESS_TOKEN}
  twitter:
    api-key: ${TWITTER_API_KEY}
    api-secret: ${TWITTER_API_SECRET}
    oauth-access-token: ${TWITTER_OAUTH_ACCESS_TOKEN}
    oauth-access-token-secret: ${TWITTER_OAUTH_ACCESS_TOKEN_SECRET}
  vault:
    url: ${VAULT_URL}
    auth-type: ${VAULT_AUTH:TOKEN}
    token: ${VAULT_TOKEN:}
    role: ${VAULT_ROLE:}
  token-service:
    vault-path: ${VAULT_OAUTH_PATH:/oauthapp}
    credentials-path: ${VAULT_SECRETS_PATH:/secrets/data}
    tokens:
      twitter:
        server: twitter
        scopes: offline.access,tweet.write,tweet.read,users.read
        pkce: true
  mailchimp:
    api-key: ${MAILCHIMP_API_KEY:}
    dc: ${MAILCHIMP_DC:}
    list-id: ${MAILCHIMP_LIST_ID:}
    newsletter-interest-id: ${MAILCHIMP_NEWSLETTER_INTEREST_ID:}
  trusted-client-scope: "${WEBSITE_CLIENT_TRUSTED_SCOPE:graphql/trusted-client}"