ALTER TABLE
    fixture_player_summary
    ADD CONSTRAINT FK_FIXTURE_PLAYER_SUMMARY_PLAYER_ID FOREIGN KEY (player_id) REFERENCES player (id) NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE
    fixture_player_summary
    ADD CONSTRAINT FK_FIXTURE_PLAYER_SUMMARY_FIXTURE_ID FOREIGN KEY (fixture_id) REFERENCES fixture (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
