ALTER TABLE pricelist_item
  ADD COLUMN IF NOT EXISTS inclusive_kit BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS specific_gender VARCHAR(6) NULL;
